image: ubuntu:latest

stages:
  - package

package for OBS:
  stage: package
  before_script:
    - DEBIAN_FRONTEND noninteractive
    - DEBCONF_NONINTERACTIVE_SEEN true
    - echo "tzdata tzdata/Areas select Europe" > /tmp/preseed.txt
    - echo "tzdata tzdata/Zones/Europe select Berlin" >> /tmp/preseed.txt
    - debconf-set-selections /tmp/preseed.txt
    - rm /etc/timezone
    - rm /etc/localtime
    - apt update
    - apt install -y tzdata
    - apt install -y devscripts debhelper dh-systemd dh-python python python-setuptools
  script:
    - ./create_source.sh
    - test -f opsipxeconfd_*.dsc
    - test -f opsipxeconfd_*.tar.gz
    - test -f opsipxeconfd.spec
  artifacts:
    paths:
      - opsipxeconfd_*.dsc
      - opsipxeconfd_*.tar.gz
      - opsipxeconfd.spec
    expire_in: 2 days
  only:
      - /^release/.*$/i
      - tags
      - web
