image: python:3.7-stretch

stages:
  - build
  - package

before_script:
  - apt update
  - apt install -y curl debhelper osc
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - pip3 install --trusted-host pypi.uib.gmbh --index-url http://pypi.uib.gmbh:8080/simple opsi-dev-tools
  - source $HOME/.poetry/env

build:linux-pyinstaller:
  stage: build
  script:
    - poetry install
    - poetry run opsi-dev-tool -l info --pyinstaller-poetry-build
    - mv opsipxeconfd opsipxeconfd.src
    - mv dist/opsipxeconfd .
    # Check if binary is working
    - ./opsipxeconfd/opsipxeconfd --help
  artifacts:
    name: 'opsipxeconfd-linux-pyinstaller'
    paths:
      - opsipxeconfd
    expire_in: 2 day

package:obs:
  stage: package
  script:
    - opsi-dev-tool -l info --obs-update-package https://obs.uib.local home:uibmz:opsi:4.2:experimental


