[tool.poetry]
name = "opsipxeconfd"
version = "4.2.0.23"
description = "opsi pxe configuration service"
homepage = "https://www.opsi.org"
license = "AGPL-3.0"
maintainers = ["uib GmbH <info@uib.de>"]
authors = ["uib GmbH <info@uib.de>"]
include = [
    "run-opsipxeconfd",
    "opsipxeconfd_data/**/*"
]

[[tool.poetry.source]]
name = "uibpypi"
url = "http://pypi.uib.gmbh:8080/simple"


[tool.poetry.dependencies]
python = ">=3.7,<3.11"
python-opsi = "^4.2.0.266"
mysqlclient = "^2.0"
distro = {platform = "linux", version = "^1.5.0"}

[tool.poetry.dev-dependencies]
opsi-dev-tools = "^1.1"
pytest = "^6.2"
pytest-cov = "^3.0"
pyinstaller = "^4.8"
pylint = "^2.12"

[tool.poetry.scripts]
opsipxeconfd = "opsipxeconfd.__main__:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
