[tool.poetry]
name = "opsipxeconfd"
version = "4.2.0"
description = "opsi pxe configuration service"
homepage = "https://www.opsi.org"
maintainers = ["uib GmbH <info@uib.de>"]
authors = ["uib GmbH <info@uib.de>"]
include = [
    "run-opsipxeconfd",
    "opsipxeconfd_data/**/*"
]

[[tool.poetry.source]]
name = "uibpypi"
url = "http://pypi.uib.gmbh:8080/simple"


[tool.poetry.dependencies]
python = "^3.6"
#python-opsi = {path = "python-opsi"}
python-opsi = "^4.2"
distro = "^1.5.0"
mysqlclient = "^1.4.6"

[tool.poetry.dev-dependencies]
pyinstaller = "^3.6"
opsi-dev-tools = "^1.0.4"
#poetry add git+<protocol>://git@<repository>/<owner>/<project>.git#<git_ref>


[tool.poetry.scripts]
opsipxeconfd = "opsipxeconfd.__main__:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
