[project]
name = "opsipxeconfd"
version = "4.3.12.0"
description = "opsi pxe configuration service"
readme = "README.md"
license = "AGPL-3.0-only"
requires-python = ">=3.11"
dependencies = [
	"python-opsi-common>=4.3.3,<4.4",
	"inotify>=0.2",
	"configargparse>=1.5",
	"py-purecrypt>=0.1",
	"jinja2>=3.1.6",
]

[[project.authors]]
name = "uib GmbH"
email = "info@uib.de"

[[project.maintainers]]
name = "uib GmbH"
email = "info@uib.de"

[dependency-groups]
dev = [
	"ruff>=0.3",
	"pytest>=8.1",
	"pytest-cov>=5.0",
	"pyinstaller>=6.2",
	"mypy>=1.7",
	# Pin setuptools to avoid warning:
	# See https://setuptools.pypa.io/en/latest/pkg_resources.html.
	# The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
	"setuptools>=71.0,<80.9",

]

[project.urls]
Homepage = "https://www.opsi.org"

[project.scripts]
opsiconfd = "opsipxeconfd.__main__:main"

[tool.uv]
extra-index-url = ["https://pypi.uib.gmbh/simple"]
index-strategy = "unsafe-best-match"
package = true

[tool.ruff]
line-length = 140

[tool.mypy]
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
follow_imports = "silent"

[tool.ruff.format]
indent-style = "tab"

[tool.setuptools.package-data]
opsipxeconfd_data = ["*"]

[tool.setuptools.packages.find]
include = [
	"opsipxeconfd",
	"opsipxeconfd.*",
	"opsipxeconfd_data",
	"opsipxeconfd_data.*",
]
