; = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
; =     configuration file for opsipxeconfd                             =
; = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

# Set the log (verbosity) level
# (0 <= log level <= 6)
# 0: nothing, 1: essential, 2: critical, 3: errors, 4: warnings, 5: notices
# 6: infos, 7: debug messages, 8: more debug messages, 9: passwords
# opsipxeconfd needs to be reloaded (SIGHUP) for changes to take effect.
#
# Default:
#   log level = 5

log level = 5

# Number of maximum simultaneous control connections.
# opsipxeconfd needs to be reloaded (SIGHUP) for changes to take effect.
#
# Default:
#   max control connections = 5

max control connections = 5

# Number of maximum simultaneous pxe config writer threads.
# opsipxeconfd needs to be reloaded (SIGHUP) for changes to take effect.
#
# Default:
#   max pxe config writers = 100

max pxe config writers = 100
